PROGRAM=./out/imagecon
OBJS=out/imagecon.o out/png.o out/color.o out/dither.o out/ham.o out/palette.o out/file.o out/sliced_ham.o out/quant.o out/utils.o
LIBS=-lpng -limagequant

include ../../shared/tools.mk

